format:
  pdf:
    pdf-engine: xelatex
    keep-tex: False
    title-block-style: none
    number-sections: true
    documentclass: scrartcl
    classoption:
      - DIV=11
      - numbers=noendperiod
    papersize: letter

jupyter: .venv
execute:
  echo: false
  warning: false
  error: false
