# Quarto project config
title: "Credit Risk EDA"
author:
  - name: PHETH Soriyuon
  - name: PHOEURN Kimhor
  - name: YIN Sambat
  - name: "Lecturered by: Dr. HAS Sothea"
date: "18 January 2026"
date-format: "DD/MM/YYYY"
format: 
  revealjs:
    slide-number: true
    progress: true
    smaller: true
    scrollable: true
    touch: true
    navigation-mode: linear
    footer: "I5-AMS (2025-2026)"
    embed-resources: true
    number-sections: true
    css: styles.css

jupyter: .venv
execute:
  echo: false
  warning: false
  error: false
